### ISSUE TITLE
怎么删除画的图形呢

### ISSUE THREAD

**Issue by 1174846885** [sHenGlinL/leaflet-plot#1]

**Comment by sHenGlinL** [comment]
删除图形直接调用leaflet的api就好了，跟插件没关系。layer.remove() 就好了

**Comment by sHenGlinL** [comment]
解决了的话给个star呗谢谢

**Comment by 1174846885** [comment]
好的 给啦， const arrowLayer = window.L.SL.Create.StraightArrow(latlngs, options) 这个是做什么的可能我比较菜没搞明白这个 ,还有一个
<img width="424" alt="image" src="https://github.com/sHenGlinL/leaflet-plot/assets/129295821/85bc7839-d1f4-4a6b-87d6-87240b7be2bf">
目前我没找到原因去解决

**Comment by sHenGlinL** [comment]
window.L.SL.Create.StraightArrow(latlngs, options)这个方法是创建直线箭头的，传入的参数文档有写。
你这个报错是传入的坐标有问题，你是什么情况下出现报错的

**Comment by 1174846885** [comment]
有时候画着画着就有问题了

**Comment by sHenGlinL** [comment]
我好像找到原因了，我修复一下，谢谢指出问题

**Comment by 1174846885** [comment]
好的

**Comment by sHenGlinL** [comment]
最新版1.0.4已经修复了你说的报错问题，你可以试试

**Comment by 1174846885** [comment]
好的👌
