### ISSUE TITLE
什么时候计划增加多一些态势标绘

### ISSUE THREAD

**Issue by echohye** [sHenGlinL/leaflet-plot#5]
你好，请问会有计划增加多一些标绘吗，例如https://blog.sakitam.com/ol-plot/
![image](https://github.com/sHenGlinL/leaflet-plot/assets/81301702/e43517f8-5f40-40ae-9899-01a3073c77c9)

还有，请问目前绘制的图像是否支持编辑？

**Comment by sHenGlinL** [comment]
目前绘制的都支持编辑。没有计划新增多的标绘诶，我现在没搞gis了。但是有bug我会修复

**Comment by echohye** [comment]
噢噢，找了许久，使用leaflet制作应急标绘的且支持编辑的，相对属你这个最好了，就是标绘支持的比较少。感谢感谢
