### ISSUE TITLE
先前事件被移除

### ISSUE THREAD

**Issue by echohye** [sHenGlinL/leaflet-plot#6]
https://github.com/sHenGlinL/leaflet-plot/blob/e0d0751e8028dfe2698d0b1359187f317600881b/src/js/Draw/L.SL.Draw.js#L56
这里会把先前定义的事件都给移除了

**Comment by sHenGlinL** [comment]
修复好了，安装1.0.5试试

**Comment by echohye** [comment]
好的🎉。请问画的图形为什么会出现变形，[ol-plot](https://github.com/sakitam-fdd/ol-plot)画出来的不会变形，对比图如下，这是算法差异的原因吗
![image](https://github.com/sHenGlinL/leaflet-plot/assets/81301702/992320e5-5474-47cf-bfd7-0c6a218602d6)
![image](https://github.com/sHenGlinL/leaflet-plot/assets/81301702/419db152-1836-48c1-936f-c9c7f716ee39)

**Comment by sHenGlinL** [comment]
这个应该跟坐标投影有关系，用的是墨卡托投影还是经纬度投影。经纬度投影画出来的会有拉伸。可以去看一下gis的基础知识
